int _parseInt(dynamic value, {int fallback = 0}) {
  if (value is num) return value.toInt();
  if (value == null) return fallback;
  return int.tryParse(value.toString()) ?? fallback;
}

double _parseDouble(dynamic value, {double fallback = 0}) {
  if (value is num) return value.toDouble();
  if (value == null) return fallback;
  return double.tryParse(value.toString()) ?? fallback;
}

int? _parseOptionalInt(dynamic value) {
  if (value is num) return value.toInt();
  if (value == null) return null;
  return int.tryParse(value.toString());
}

double? _parseOptionalDouble(dynamic value) {
  if (value is num) return value.toDouble();
  if (value == null) return null;
  return double.tryParse(value.toString());
}

class TrainingNeedItem {
  TrainingNeedItem({
    required this.id,
    required this.topic,
    required this.timeframe,
    required this.format,
    required this.participants,
    required this.budget,
    required this.requirements,
  });

  final String id;
  final String topic;
  final String timeframe;
  final String format;
  final int participants;
  final double budget;
  final String requirements;

  factory TrainingNeedItem.fromJson(Map<String, dynamic> json) {
    return TrainingNeedItem(
      id: (json['id'] ?? '').toString(),
      topic: (json['topic'] ?? '').toString(),
      timeframe: (json['timeframe'] ?? '').toString(),
      format: (json['format'] ?? '').toString(),
      participants: _parseInt(json['participants']),
      budget: _parseDouble(json['budget']),
      requirements: (json['requirements'] ?? '').toString(),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'topic': topic,
        'timeframe': timeframe,
        'format': format,
        'participants': participants,
        'budget': budget,
        'requirements': requirements,
      };
}

class TrainingNeed {
  TrainingNeed({
    required this.id,
    required this.year,
    required this.contactName,
    required this.position,
    required this.department,
    required this.team,
    required this.items,
    required this.comments,
    required this.departmentTeamSelected,
    required this.departmentTeamFreeText,
    required this.plannedPeriodType,
    required this.plannedPeriodValue,
    required this.trainingFormat,
    required this.intervalType,
    required this.intervalValue,
    required this.intervalValueFreeText,
    required this.plannedBudget,
    required this.additionalNotes,
    required this.topicPriorities,
    required this.preferredTrainers,
    required this.specialRequirements,
    required this.status,
    required this.noNeed,
    this.recurrenceIntervalMonths,
    this.nextDuePeriod,
    this.recurrenceActive = true,
    this.lastGeneratedAt,
    this.parentRecurringId,
    this.isAutoGenerated = false,
    this.integratedAt,
    this.integratedByUserId,
    this.createdAt,
    this.updatedAt,
  });

  final String id;
  final int year;
  final String contactName;
  final String position;
  final String department;
  final String team;
  final List<TrainingNeedItem> items;
  final String comments;
  final String departmentTeamSelected;
  final String? departmentTeamFreeText;
  final String plannedPeriodType;
  final String plannedPeriodValue;
  final String trainingFormat;
  final String intervalType;
  final String? intervalValue;
  final String? intervalValueFreeText;
  final double? plannedBudget;
  final String? additionalNotes;
  final String? topicPriorities;
  final String? preferredTrainers;
  final String? specialRequirements;
  final String status;
  final bool noNeed;
  final int? recurrenceIntervalMonths;
  final String? nextDuePeriod;
  final bool recurrenceActive;
  final int? lastGeneratedAt;
  final String? parentRecurringId;
  final bool isAutoGenerated;
  final int? integratedAt;
  final String? integratedByUserId;
  final int? createdAt;
  final int? updatedAt;

  factory TrainingNeed.fromJson(Map<String, dynamic> json) {
    return TrainingNeed(
      id: (json['id'] ?? '').toString(),
      year: _parseInt(json['year']),
      contactName: (json['contactName'] ?? '').toString(),
      position: (json['position'] ?? '').toString(),
      department: (json['department'] ?? '').toString(),
      team: (json['team'] ?? '').toString(),
      items: (json['items'] as List? ?? [])
          .whereType<Map>()
          .map((item) => TrainingNeedItem.fromJson(item.cast<String, dynamic>()))
          .toList(),
      comments: (json['comments'] ?? '').toString(),
      departmentTeamSelected: (json['departmentTeamSelected'] ?? json['departmentTeam'] ?? '').toString(),
      departmentTeamFreeText: (json['departmentTeamFreeText'] ?? json['departmentTeamOther'])?.toString(),
      plannedPeriodType: (json['plannedPeriodType'] ?? '').toString(),
      plannedPeriodValue: (json['plannedPeriodValue'] ?? '').toString(),
      trainingFormat: (() {
        final raw = json['trainingFormat'];
        if (raw != null) return raw.toString();
        final items = json['items'];
        if (items is List && items.isNotEmpty) {
          final first = items.first;
          if (first is Map && first['format'] != null) return first['format'].toString();
        }
        return '';
      })(),
      intervalType: (json['intervalType'] ?? '').toString(),
      intervalValue: (json['intervalValue'] ?? '').toString().isEmpty ? null : (json['intervalValue'] ?? '').toString(),
      intervalValueFreeText:
          (json['intervalValueFreeText'] ?? '').toString().isEmpty ? null : (json['intervalValueFreeText'] ?? '').toString(),
      plannedBudget: _parseOptionalDouble(json['plannedBudget'] ?? json['budget']),
      additionalNotes: (json['additionalNotes'] ?? json['comments'])?.toString(),
      topicPriorities: (json['topicPriorities'] ?? '').toString().isEmpty ? null : (json['topicPriorities'] ?? '').toString(),
      preferredTrainers:
          (json['preferredTrainers'] ?? '').toString().isEmpty ? null : (json['preferredTrainers'] ?? '').toString(),
      specialRequirements:
          (json['specialRequirements'] ?? '').toString().isEmpty ? null : (json['specialRequirements'] ?? '').toString(),
      status: (json['status'] ?? '').toString(),
      noNeed: json['noNeed'] == true,
      recurrenceIntervalMonths: _parseOptionalInt(json['recurrenceIntervalMonths']),
      nextDuePeriod: (json['nextDuePeriod'] ?? '').toString().isEmpty ? null : (json['nextDuePeriod'] ?? '').toString(),
      recurrenceActive: json['recurrenceActive'] != false,
      lastGeneratedAt: _parseOptionalInt(json['lastGeneratedAt']),
      parentRecurringId:
          (json['parentRecurringId'] ?? '').toString().isEmpty ? null : (json['parentRecurringId'] ?? '').toString(),
      isAutoGenerated: json['isAutoGenerated'] == true,
      integratedAt: json['integratedAt'] == null ? null : _parseInt(json['integratedAt']),
      integratedByUserId:
          (json['integratedByUserId'] ?? '').toString().isEmpty ? null : (json['integratedByUserId'] ?? '').toString(),
      createdAt: json['createdAt'] == null ? null : _parseInt(json['createdAt']),
      updatedAt: json['updatedAt'] == null ? null : _parseInt(json['updatedAt']),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'year': year,
        'contactName': contactName,
        'position': position,
        'department': department,
        'team': team,
        'items': items.map((item) => item.toJson()).toList(),
        'comments': comments,
        'departmentTeamSelected': departmentTeamSelected,
        'departmentTeamFreeText': departmentTeamFreeText,
        'plannedPeriodType': plannedPeriodType,
        'plannedPeriodValue': plannedPeriodValue,
        'trainingFormat': trainingFormat,
        'intervalType': intervalType,
        'intervalValue': intervalValue,
        'intervalValueFreeText': intervalValueFreeText,
        'plannedBudget': plannedBudget,
        'additionalNotes': additionalNotes,
        'topicPriorities': topicPriorities,
        'preferredTrainers': preferredTrainers,
        'specialRequirements': specialRequirements,
        'status': status,
        'noNeed': noNeed,
        'recurrenceIntervalMonths': recurrenceIntervalMonths,
        'nextDuePeriod': nextDuePeriod,
        'recurrenceActive': recurrenceActive,
        'lastGeneratedAt': lastGeneratedAt,
        'parentRecurringId': parentRecurringId,
        'isAutoGenerated': isAutoGenerated,
        'integratedAt': integratedAt,
        'integratedByUserId': integratedByUserId,
        'createdAt': createdAt,
        'updatedAt': updatedAt,
      };
}

class TrainingNeedSubmitResult {
  TrainingNeedSubmitResult({required this.need, this.warning});

  final TrainingNeed need;
  final String? warning;
}

class TrainingProgramNeedLink {
  TrainingProgramNeedLink({
    required this.id,
    required this.programEntryId,
    required this.trainingNeedId,
    required this.linkedAt,
    required this.linkedByUserId,
  });

  final String id;
  final String programEntryId;
  final String trainingNeedId;
  final int linkedAt;
  final String linkedByUserId;

  factory TrainingProgramNeedLink.fromJson(Map<String, dynamic> json) {
    return TrainingProgramNeedLink(
      id: (json['id'] ?? '').toString(),
      programEntryId: (json['programEntryId'] ?? json['programId'] ?? '').toString(),
      trainingNeedId: (json['trainingNeedId'] ?? json['needId'] ?? '').toString(),
      linkedAt: _parseInt(json['linkedAt']),
      linkedByUserId: (json['linkedByUserId'] ?? json['linkedBy'] ?? '').toString(),
    );
  }
}

class TrainingProgram {
  TrainingProgram({
    required this.id,
    required this.year,
    required this.title,
    required this.status,
    required this.owner,
    required this.department,
    required this.targetGroup,
    required this.category,
    this.categoryFreeText,
    required this.plannedPeriodType,
    required this.plannedPeriodValue,
    required this.format,
    required this.intervalType,
    this.intervalValue,
    required this.responsiblePerson,
    required this.participantsPlanned,
    required this.trainerProvider,
    required this.location,
    required this.duration,
    required this.notes,
    required this.cancellationReason,
    required this.needIds,
    this.needLinks = const [],
    required this.trainingIds,
    required this.budgetTotal,
    this.updatedAt,
  });

  final String id;
  final int year;
  final String title;
  final String status;
  final String owner;
  final String department;
  final String targetGroup;
  final String category;
  final String? categoryFreeText;
  final String plannedPeriodType;
  final String plannedPeriodValue;
  final String format;
  final String intervalType;
  final String? intervalValue;
  final String responsiblePerson;
  final String participantsPlanned;
  final String trainerProvider;
  final String location;
  final String duration;
  final String notes;
  final String? cancellationReason;
  final List<String> needIds;
  final List<TrainingProgramNeedLink> needLinks;
  final List<String> trainingIds;
  final double budgetTotal;
  final int? updatedAt;

  factory TrainingProgram.fromJson(Map<String, dynamic> json) {
    return TrainingProgram(
      id: (json['id'] ?? '').toString(),
      year: _parseInt(json['year']),
      title: (json['title'] ?? '').toString(),
      status: (json['status'] ?? '').toString(),
      owner: (json['owner'] ?? '').toString(),
      department: (json['department'] ?? '').toString(),
      targetGroup: (json['targetGroup'] ?? '').toString(),
      category: (json['category'] ?? '').toString(),
      categoryFreeText: (json['categoryFreeText'] ?? '').toString().isEmpty ? null : (json['categoryFreeText'] ?? '').toString(),
      plannedPeriodType: (json['plannedPeriodType'] ?? '').toString(),
      plannedPeriodValue: (json['plannedPeriodValue'] ?? '').toString(),
      format: (json['format'] ?? '').toString(),
      intervalType: (json['intervalType'] ?? '').toString(),
      intervalValue: (json['intervalValue'] ?? '').toString().isEmpty ? null : (json['intervalValue'] ?? '').toString(),
      responsiblePerson: (json['responsiblePerson'] ?? '').toString(),
      participantsPlanned: (json['participantsPlanned'] ?? '').toString(),
      trainerProvider: (json['trainerProvider'] ?? '').toString(),
      location: (json['location'] ?? '').toString(),
      duration: (json['duration'] ?? '').toString(),
      notes: (json['notes'] ?? '').toString(),
      cancellationReason: json['cancellationReason']?.toString(),
      needIds: (json['needIds'] as List? ?? []).map((e) => e.toString()).toList(),
      needLinks: (json['needLinks'] as List? ?? [])
          .whereType<Map>()
          .map((e) => TrainingProgramNeedLink.fromJson(e.cast<String, dynamic>()))
          .toList(),
      trainingIds: (json['trainingIds'] as List? ?? []).map((e) => e.toString()).toList(),
      budgetTotal: _parseDouble(json['budgetTotal']),
      updatedAt: json['updatedAt'] == null ? null : _parseInt(json['updatedAt']),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'year': year,
        'title': title,
        'status': status,
        'owner': owner,
        'department': department,
        'targetGroup': targetGroup,
        'category': category,
        'categoryFreeText': categoryFreeText,
        'plannedPeriodType': plannedPeriodType,
        'plannedPeriodValue': plannedPeriodValue,
        'format': format,
        'intervalType': intervalType,
        'intervalValue': intervalValue,
        'responsiblePerson': responsiblePerson,
        'participantsPlanned': participantsPlanned,
        'trainerProvider': trainerProvider,
        'location': location,
        'duration': duration,
        'notes': notes,
        'cancellationReason': cancellationReason,
        'needIds': needIds,
        'needLinks': needLinks
            .map((link) => {
                  'id': link.id,
                  'programEntryId': link.programEntryId,
                  'trainingNeedId': link.trainingNeedId,
                  'linkedAt': link.linkedAt,
                  'linkedByUserId': link.linkedByUserId,
                })
            .toList(),
        'trainingIds': trainingIds,
        'budgetTotal': budgetTotal,
        'updatedAt': updatedAt,
      };
}

class TrainingParticipant {
  TrainingParticipant({
    required this.id,
    required this.userId,
    required this.name,
    required this.email,
    required this.status,
    required this.external,
    this.departmentTeam,
    this.signedAt,
    this.signedByUserId,
    this.signatureBase64,
    this.signatureUrl,
    this.signatureHash,
    this.signatureNote,
    this.overrideNoSignature = false,
    this.overrideReason,
    this.overriddenByUserId,
    this.overriddenAt,
  });

  final String id;
  final String userId;
  final String name;
  final String email;
  final String status;
  final bool external;
  final String? departmentTeam;
  final int? signedAt;
  final String? signedByUserId;
  final String? signatureBase64;
  final String? signatureUrl;
  final String? signatureHash;
  final String? signatureNote;
  final bool overrideNoSignature;
  final String? overrideReason;
  final String? overriddenByUserId;
  final int? overriddenAt;

  factory TrainingParticipant.fromJson(Map<String, dynamic> json) {
    return TrainingParticipant(
      id: (json['id'] ?? '').toString(),
      userId: (json['userId'] ?? json['participantUserId'] ?? json['email'] ?? '').toString(),
      name: (json['name'] ?? '').toString(),
      email: (json['email'] ?? '').toString(),
      status: (json['status'] ?? '').toString(),
      external: json['external'] == true,
      departmentTeam: (json['departmentTeam'] ?? '').toString().isEmpty ? null : (json['departmentTeam'] ?? '').toString(),
      signedAt: json['signedAt'] == null ? null : _parseInt(json['signedAt']),
      signedByUserId: (json['signedByUserId'] ?? json['signedBy'] ?? '').toString().isEmpty
          ? null
          : (json['signedByUserId'] ?? json['signedBy'] ?? '').toString(),
      signatureBase64: (json['signatureBase64'] ?? '').toString().isEmpty ? null : (json['signatureBase64'] ?? '').toString(),
      signatureUrl: (json['signatureUrl'] ?? '').toString().isEmpty ? null : (json['signatureUrl'] ?? '').toString(),
      signatureHash: (json['signatureHash'] ?? '').toString().isEmpty ? null : (json['signatureHash'] ?? '').toString(),
      signatureNote: (json['signatureNote'] ?? '').toString().isEmpty ? null : (json['signatureNote'] ?? '').toString(),
      overrideNoSignature: json['overrideNoSignature'] == true,
      overrideReason: (json['overrideReason'] ?? '').toString().isEmpty ? null : (json['overrideReason'] ?? '').toString(),
      overriddenByUserId: (json['overriddenByUserId'] ?? '').toString().isEmpty
          ? null
          : (json['overriddenByUserId'] ?? '').toString(),
      overriddenAt: json['overriddenAt'] == null ? null : _parseInt(json['overriddenAt']),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'name': name,
        'email': email,
        'status': status,
        'external': external,
        'departmentTeam': departmentTeam,
        'signedAt': signedAt,
        'signedByUserId': signedByUserId,
        'signatureBase64': signatureBase64,
        'signatureUrl': signatureUrl,
        'signatureHash': signatureHash,
        'signatureNote': signatureNote,
        'overrideNoSignature': overrideNoSignature,
        'overrideReason': overrideReason,
        'overriddenByUserId': overriddenByUserId,
        'overriddenAt': overriddenAt,
      };

  String get department => departmentTeam ?? '';

  bool get isSigned => signedAt != null || overrideNoSignature;
}

class TrainingRecord {
  TrainingRecord({
    required this.id,
    required this.trainingNumber,
    required this.year,
    required this.title,
    required this.category,
    required this.type,
    required this.format,
    required this.startDate,
    required this.endDate,
    required this.trainer,
    required this.location,
    required this.status,
    required this.owner,
    required this.targetGroup,
    required this.reason,
    required this.departments,
    required this.isMandatory,
    required this.isExternal,
    required this.participants,
    required this.defaultQuestionnaireTemplateId,
    this.completedAt,
    this.wkMethod,
    this.wkDelayDays,
    this.wkDueAt,
    this.wkStatus,
    this.wkCompletedAt,
    this.wkResponsibleId,
    this.wkQuestionnaireTemplateId,
    this.wkThresholdPercent,
    this.wkTargetParticipantIds,
    this.auditLog = const [],
    this.linkedProgramId,
    this.intervalType,
    this.intervalValue,
    this.recurrenceIntervalMonths,
    this.nextDueDate,
    this.recurrenceActive = true,
    this.lastGeneratedAt,
    this.parentRecurringId,
    this.isAutoGenerated = false,
    this.actualParticipants,
    this.executionNotes,
    this.effectivenessResult,
    this.updatedAt,
    this.categoryFreeText,
    this.startTime,
    this.endTime,
    this.meetingLink,
    this.platform,
    this.trainerInternal,
    this.providerCompany,
    this.ownerUserId,
    this.notes,
  });

  final String id;
  final String trainingNumber;
  final int year;
  final String title;
  final String category;
  final String type;
  final String format;
  final String startDate;
  final String endDate;
  final String trainer;
  final String location;
  final String status;
  final String owner;
  final String targetGroup;
  final String reason;
  final List<String> departments;
  final bool isMandatory;
  final bool isExternal;
  final List<TrainingParticipant> participants;
  final String defaultQuestionnaireTemplateId;
  final int? completedAt;
  final String? wkMethod;
  final int? wkDelayDays;
  final int? wkDueAt;
  final String? wkStatus;
  final int? wkCompletedAt;
  final String? wkResponsibleId;
  final String? wkQuestionnaireTemplateId;
  final int? wkThresholdPercent;
  final List<String>? wkTargetParticipantIds;
  final List<TrainingAuditLogEntry> auditLog;
  final String? linkedProgramId;
  final String? intervalType;
  final String? intervalValue;
  final int? recurrenceIntervalMonths;
  final String? nextDueDate;
  final bool recurrenceActive;
  final int? lastGeneratedAt;
  final String? parentRecurringId;
  final bool isAutoGenerated;
  final int? actualParticipants;
  final String? executionNotes;
  final String? effectivenessResult;
  final int? updatedAt;
  final String? categoryFreeText;
  final String? startTime;
  final String? endTime;
  final String? meetingLink;
  final String? platform;
  final String? trainerInternal;
  final String? providerCompany;
  final String? ownerUserId;
  final String? notes;

  factory TrainingRecord.fromJson(Map<String, dynamic> json) {
    return TrainingRecord(
      id: (json['id'] ?? '').toString(),
      trainingNumber: (json['trainingNumber'] ?? '').toString(),
      year: _parseInt(json['year']),
      title: (json['title'] ?? '').toString(),
      category: (json['category'] ?? '').toString(),
      type: (json['type'] ?? '').toString(),
      format: (json['format'] ?? '').toString(),
      startDate: (json['startDate'] ?? '').toString(),
      endDate: (json['endDate'] ?? '').toString(),
      trainer: (json['trainer'] ?? '').toString(),
      location: (json['location'] ?? '').toString(),
      status: (json['status'] ?? '').toString(),
      owner: (json['owner'] ?? '').toString(),
      targetGroup: (json['targetGroup'] ?? '').toString(),
      reason: (json['reason'] ?? '').toString(),
      departments: (json['departments'] as List? ?? []).map((e) => e.toString()).toList(),
      isMandatory: json['isMandatory'] == true,
      isExternal: json['isExternal'] == true,
      participants: (json['participants'] as List? ?? [])
          .whereType<Map>()
          .map((item) => TrainingParticipant.fromJson(item.cast<String, dynamic>()))
          .toList(),
      defaultQuestionnaireTemplateId: (json['defaultQuestionnaireTemplateId'] ?? '').toString(),
      completedAt: json['completedAt'] == null ? null : _parseInt(json['completedAt']),
      wkMethod: (json['wkMethod'] ?? '').toString().isEmpty ? null : (json['wkMethod'] ?? '').toString(),
      wkDelayDays: json['wkDelayDays'] == null ? null : _parseInt(json['wkDelayDays']),
      wkDueAt: json['wkDueAt'] == null ? null : _parseInt(json['wkDueAt']),
      wkStatus: (json['wkStatus'] ?? '').toString().isEmpty ? null : (json['wkStatus'] ?? '').toString(),
      wkCompletedAt: json['wkCompletedAt'] == null ? null : _parseInt(json['wkCompletedAt']),
      wkResponsibleId: (json['wkResponsibleId'] ?? '').toString().isEmpty ? null : (json['wkResponsibleId'] ?? '').toString(),
      wkQuestionnaireTemplateId: (json['wkQuestionnaireTemplateId'] ?? '').toString().isEmpty
          ? null
          : (json['wkQuestionnaireTemplateId'] ?? '').toString(),
      wkThresholdPercent: json['wkThresholdPercent'] == null ? null : _parseInt(json['wkThresholdPercent']),
      wkTargetParticipantIds: (json['wkTargetParticipantIds'] as List? ?? []).map((e) => e.toString()).toList(),
      auditLog: (json['auditLog'] as List? ?? [])
          .whereType<Map>()
          .map((entry) => TrainingAuditLogEntry.fromJson(entry.cast<String, dynamic>()))
          .toList(),
      intervalType: (json['intervalType'] ?? '').toString().isEmpty ? null : (json['intervalType'] ?? '').toString(),
      intervalValue: (json['intervalValue'] ?? '').toString().isEmpty ? null : (json['intervalValue'] ?? '').toString(),
      recurrenceIntervalMonths: _parseOptionalInt(json['recurrenceIntervalMonths']),
      nextDueDate: (json['nextDueDate'] ?? '').toString().isEmpty ? null : (json['nextDueDate'] ?? '').toString(),
      recurrenceActive: json['recurrenceActive'] != false,
      lastGeneratedAt: _parseOptionalInt(json['lastGeneratedAt']),
      parentRecurringId:
          (json['parentRecurringId'] ?? '').toString().isEmpty ? null : (json['parentRecurringId'] ?? '').toString(),
      isAutoGenerated: json['isAutoGenerated'] == true,
      linkedProgramId: json['linkedProgramId']?.toString(),
      actualParticipants: json['actualParticipants'] == null ? null : _parseInt(json['actualParticipants']),
      executionNotes: json['executionNotes']?.toString(),
      effectivenessResult: json['effectivenessResult']?.toString(),
      updatedAt: json['updatedAt'] == null ? null : _parseInt(json['updatedAt']),
      categoryFreeText: json['categoryFreeText']?.toString(),
      startTime: json['startTime']?.toString(),
      endTime: json['endTime']?.toString(),
      meetingLink: json['meetingLink']?.toString(),
      platform: json['platform']?.toString(),
      trainerInternal: json['trainerInternal']?.toString(),
      providerCompany: json['providerCompany']?.toString(),
      ownerUserId: json['ownerUserId']?.toString(),
      notes: json['notes']?.toString(),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'trainingNumber': trainingNumber,
        'year': year,
        'title': title,
        'category': category,
        'type': type,
        'format': format,
        'startDate': startDate,
        'endDate': endDate,
        'trainer': trainer,
        'location': location,
        'status': status,
        'owner': owner,
        'targetGroup': targetGroup,
        'reason': reason,
        'departments': departments,
        'isMandatory': isMandatory,
        'isExternal': isExternal,
        'participants': participants.map((p) => p.toJson()).toList(),
        'defaultQuestionnaireTemplateId': defaultQuestionnaireTemplateId,
        'completedAt': completedAt,
        'wkMethod': wkMethod,
        'wkDelayDays': wkDelayDays,
        'wkDueAt': wkDueAt,
        'wkStatus': wkStatus,
        'wkCompletedAt': wkCompletedAt,
        'wkResponsibleId': wkResponsibleId,
        'wkQuestionnaireTemplateId': wkQuestionnaireTemplateId,
        'wkThresholdPercent': wkThresholdPercent,
        'wkTargetParticipantIds': wkTargetParticipantIds,
        'auditLog': auditLog.map((entry) => entry.toJson()).toList(),
        'intervalType': intervalType,
        'intervalValue': intervalValue,
        'recurrenceIntervalMonths': recurrenceIntervalMonths,
        'nextDueDate': nextDueDate,
        'recurrenceActive': recurrenceActive,
        'lastGeneratedAt': lastGeneratedAt,
        'parentRecurringId': parentRecurringId,
        'isAutoGenerated': isAutoGenerated,
        'linkedProgramId': linkedProgramId,
        'actualParticipants': actualParticipants,
        'executionNotes': executionNotes,
        'effectivenessResult': effectivenessResult,
        'updatedAt': updatedAt,
        'categoryFreeText': categoryFreeText,
        'startTime': startTime,
        'endTime': endTime,
        'meetingLink': meetingLink,
        'platform': platform,
        'trainerInternal': trainerInternal,
        'providerCompany': providerCompany,
        'ownerUserId': ownerUserId,
        'notes': notes,
      };
}

class TrainingWkAssessment {
  TrainingWkAssessment({
    required this.id,
    required this.trainingSessionId,
    required this.assessmentType,
    required this.performedAt,
    required this.performedByUserId,
    required this.result,
    this.notes,
  });

  final String id;
  final String trainingSessionId;
  final String assessmentType;
  final int? performedAt;
  final String performedByUserId;
  final String result;
  final String? notes;

  factory TrainingWkAssessment.fromJson(Map<String, dynamic> json) => TrainingWkAssessment(
        id: (json['id'] ?? '').toString(),
        trainingSessionId: (json['trainingSessionId'] ?? json['trainingId'] ?? '').toString(),
        assessmentType: (json['assessmentType'] ?? '').toString(),
        performedAt: json['performedAt'] == null ? null : _parseInt(json['performedAt']),
        performedByUserId: (json['performedByUserId'] ?? '').toString(),
        result: (json['result'] ?? '').toString(),
        notes: (json['notes'] ?? '').toString().isEmpty ? null : (json['notes'] ?? '').toString(),
      );
}

class TrainingAuditLogEntry {
  TrainingAuditLogEntry({
    required this.id,
    required this.action,
    required this.message,
    required this.by,
    required this.at,
  });

  final String id;
  final String action;
  final String message;
  final String by;
  final int? at;

  factory TrainingAuditLogEntry.fromJson(Map<String, dynamic> json) => TrainingAuditLogEntry(
        id: (json['id'] ?? '').toString(),
        action: (json['action'] ?? '').toString(),
        message: (json['message'] ?? '').toString(),
        by: (json['by'] ?? json['user'] ?? '').toString(),
        at: json['at'] == null ? null : _parseInt(json['at']),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'action': action,
        'message': message,
        'by': by,
        'at': at,
      };
}

class TrainingQuestionnaireTemplate {
  TrainingQuestionnaireTemplate({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.tags,
    required this.estimatedDurationMinutes,
    required this.defaultThresholdPercent,
    required this.isActive,
    required this.createdBy,
    required this.updatedBy,
    required this.createdAt,
    required this.updatedAt,
    required this.questions,
  });

  final String id;
  final String title;
  final String description;
  final String category;
  final List<String> tags;
  final int? estimatedDurationMinutes;
  final int defaultThresholdPercent;
  final bool isActive;
  final String createdBy;
  final String updatedBy;
  final int? createdAt;
  final int? updatedAt;
  final List<QuestionnaireQuestion> questions;

  factory TrainingQuestionnaireTemplate.fromJson(Map<String, dynamic> json) {
    return TrainingQuestionnaireTemplate(
      id: (json['id'] ?? '').toString(),
      title: (json['title'] ?? '').toString(),
      description: (json['description'] ?? '').toString(),
      category: (json['category'] ?? '').toString(),
      tags: (json['tags'] as List? ?? []).map((e) => e.toString()).where((e) => e.isNotEmpty).toList(),
      estimatedDurationMinutes: json['estimatedDurationMinutes'] == null ? null : _parseOptionalInt(json['estimatedDurationMinutes']),
      defaultThresholdPercent: json['defaultThresholdPercent'] == null ? 0 : _parseInt(json['defaultThresholdPercent']),
      isActive: json['isActive'] != false,
      createdBy: (json['createdBy'] ?? '').toString(),
      updatedBy: (json['updatedBy'] ?? '').toString(),
      createdAt: json['createdAt'] == null ? null : _parseOptionalInt(json['createdAt']),
      updatedAt: json['updatedAt'] == null ? null : _parseOptionalInt(json['updatedAt']),
      questions: (json['questions'] as List? ?? [])
          .whereType<Map>()
          .map((item) => QuestionnaireQuestion.fromJson(item.cast<String, dynamic>()))
          .toList(),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'category': category,
        'tags': tags,
        'estimatedDurationMinutes': estimatedDurationMinutes,
        'defaultThresholdPercent': defaultThresholdPercent,
        'isActive': isActive,
        'createdBy': createdBy,
        'updatedBy': updatedBy,
        'createdAt': createdAt,
        'updatedAt': updatedAt,
        'questions': questions.map((q) => q.toJson()).toList(),
      };
}

class QuestionnaireQuestion {
  QuestionnaireQuestion({
    required this.id,
    required this.orderIndex,
    required this.type,
    required this.text,
    required this.points,
    required this.explanation,
    required this.options,
  });

  final String id;
  final int orderIndex;
  final String type;
  final String text;
  final int points;
  final String explanation;
  final List<QuestionnaireOption> options;

  factory QuestionnaireQuestion.fromJson(Map<String, dynamic> json) => QuestionnaireQuestion(
        id: (json['id'] ?? '').toString(),
        orderIndex: json['orderIndex'] == null ? 0 : _parseInt(json['orderIndex']),
        type: (json['type'] ?? '').toString(),
        text: (json['text'] ?? json['label'] ?? '').toString(),
        points: json['points'] == null ? 1 : _parseInt(json['points']),
        explanation: (json['explanation'] ?? '').toString(),
        options: (json['options'] as List? ?? [])
            .whereType<Map>()
            .map((item) => QuestionnaireOption.fromJson(item.cast<String, dynamic>()))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'orderIndex': orderIndex,
        'type': type,
        'text': text,
        'points': points,
        'explanation': explanation,
        'options': options.map((o) => o.toJson()).toList(),
      };
}

class QuestionnaireOption {
  QuestionnaireOption({
    required this.id,
    required this.orderIndex,
    required this.text,
    required this.isCorrect,
  });

  final String id;
  final int orderIndex;
  final String text;
  final bool isCorrect;

  factory QuestionnaireOption.fromJson(Map<String, dynamic> json) => QuestionnaireOption(
        id: (json['id'] ?? '').toString(),
        orderIndex: json['orderIndex'] == null ? 0 : _parseInt(json['orderIndex']),
        text: (json['text'] ?? '').toString(),
        isCorrect: json['isCorrect'] == true,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'orderIndex': orderIndex,
        'text': text,
        'isCorrect': isCorrect,
      };
}
