arb-dir: lib/l10n
template-arb-file: app_de.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/l10n_untranslated.json
synthetic-package: true
